<?php

return array(
  'dashboard' =>
  array(
    'totalClients' => 'Toplam Müvekkil',
    'totalEmployees' => 'Bütün Çalışanlar',
    'totalProjects' => 'Toplam Projeler',
    'totalPaidInvoices' => 'Ödenen Faturalar',
    'totalHoursLogged' => 'Günlüğe Kaydedilen Saatler',
    'totalPendingTasks' => 'Bekleyen görevler',
    'totalCompletedTasks' => 'Tamamlanmış Görevler',
    'totalPendingIssues' => 'Toplam Bekleyen Sorunlar',
    'totalPaidAmount' => 'Ödenen Miktar',
    'totalOutstandingAmount' => 'Ödenmemiş Tutar',
    'recentEarnings' => 'Son Kazançlar',
    'overdueTasks' => 'Gecikmiş Görevler',
    'pendingClientIssues' => 'Bekleyen Sorunlar',
    'projectActivityTimeline' => 'Proje Faaliyet Zaman Çizelgesi',
    'userActivityTimeline' => 'Kullanıcı Etkinliği Zaman Çizelgesi',
    'dueDate' => 'Bitiş tarihi',
    'weatherSetLocation' => 'Hava durumunu görmek için mevcut konumu ayarlayın',
    'totalTodayAttendance' => 'Bugün Katılım',
    'newTickets' => 'Yeni Biletler',
    'totalUnpaidInvoices' => 'Ödenmemiş Faturalar',
    'followUpDate' => 'Takip Tarihi',
    'pendingFollowUp' => 'Bekleyen Takip',
    'totalLeads' => 'Toplam Potansiyel Müvekkiller',
    'totalConvertedClient' => 'Toplam Müvekkil Dönüştürme',
    'totalPendingFollowUps' => 'Toplam Bekleyen Takip',
    'nextFollowUp' => 'Sonraki Takip',
    'holidayCheck' => 'Bugün tatil için',
    'totalArchiveProjects' => 'Toplam Arşivlenen Projeler',
    'freeEmployees' => 'Proje üzerinde çalışmıyor',
    'totalCompanies' => 'Toplam Şirketler',
    'activeCompanies' => 'Aktif Şirketler',
    'licenseExpired' => 'Lisans Süresi Doldu',
    'inactiveCompanies' => 'Aktif Olmayan Şirketler',
    'dashboardWidgets' => 'Pano Widget`ları',
    'clientFeedback' => 'Müvekkil Geri Bildirimi',
    'totalResolvedTickets' => 'Toplam Çözümlenen Biletler',
    'totalUnresolvedTickets' => 'Toplam Çözümlenmemiş Biletler',
    'settingsLeaves' => 'Ayarlar Yaprakları',
    'completedTasks' => 'Tamamlanmış Görevler',
    'clientFeedbacks' => 'Müvekkil Geri Bildirimleri',
    'totalContractsSigned' => 'Toplam İmzalanan Sözleşmeler',
    'totalContractsGenerated' => 'Üretilen Toplam Sözleşmeler',
    'totalLeadConversions' => 'Toplam Potansiyel Müvekkil Dönüşümleri',
    'latestClient' => 'Son Müvekkiller',
    'recentLoginActivities' => 'Son Giriş Etkinlikleri',
    'clientWiseEarnings' => 'Müvekkil Yönünden Kazanç',
    'clientWiseTimelogs' => 'Müvekkil Bilge Zaman Günlükleri',
    'leadVsStatus' => 'Duruma Göre Müvekkil Adayları Sayısı',
    'leadVsSource' => 'Kaynağa Göre Müvekkil Adayları Sayısı',
    'totalExpenses' => 'Toplam Giderler',
    'totalEarnings' => 'Toplam Kazanç',
    'totalProfit' => 'Toplam Kar',
    'totalPendingAmount' => 'Toplam Bekleyen Tutar',
    'earningsByClient' => 'Müvekkil Tarafından Kazanç',
    'earningsByProjects' => 'Projelere Göre Kazançlar',
    'lastReceivedPayments' => 'Son Alınan Ödemeler',
    'invoiceTab' => 'Faturalar',
    'estimateTab' => 'Tahminler',
    'expenseTab' => 'Masraflar',
    'paymentTab' => 'Ödemeler',
    'duePaymentsTab' => 'Vadesi Gelen Ödemeler',
    'proposalTab' => 'Teklifler',
    'invoiceOverview' => 'Faturaya Genel Bakış',
    'invoiceDraft' => 'Taslak',
    'invoiceNotSent' => 'Gönderilmedi',
    'invoiceUnpaid' => 'Ödenmemiş',
    'invoicePartiallyPaid' => 'Kısmen Ödenmiş',
    'invoiceOverdue' => 'Vadesi Geçmiş',
    'invoicePaid' => 'Ücretli',
    'estimateOverview' => 'Tahmine Genel Bakış',
    'estimateDraft' => 'Taslak',
    'estimateNotSent' => 'Gönderilmedi',
    'estimateSent' => 'Gönderildi',
    'estimateExpired' => 'Süresi Doldu',
    'estimateDeclined' => 'Reddedildi',
    'estimateAccepted' => 'Kabul edilmiş',
    'proposalOverview' => 'Teklife Genel Bakış',
    'proposalWaiting' => 'Beklemek',
    'proposalConverted' => 'Dönüştürülmüş',
    'proposalDeclined' => 'Reddedildi',
    'proposalAccepted' => 'Kabul edilmiş',
    'proposalExpired' => 'Süresi doldu',
    'totalLeavesApproved' => 'Toplam Yaprak Onaylandı',
    'totalNewEmployee' => 'Toplam Yeni Çalışan',
    'totalEmployeeExits' => 'Toplam Çalışan Çıkışları',
    'departmentWiseEmployee' => 'Departman Bilge Çalışanı',
    'designationWiseEmployee' => 'Atama Bilge Çalışan',
    'genderWiseEmployee' => 'Cinsiyet Bilge Çalışan',
    'roleWiseEmployee' => 'Rol Bilge Çalışan',
    'averageAttendance' => 'Ortalama Katılım',
    'leavesTaken' => 'Alınan Yapraklar',
    'lateAttendanceMark' => 'Geç Katılım İşareti',
    'lateMark' => 'Geç İşareti',
    'totalProject' => 'Toplam Projeler',
    'totalOverdueProject' => 'Toplam Gecikmiş Proje',
    'statusWiseProject' => 'Durum Bilge Projeler',
    'pendingMilestone' => 'Bekleyen Kilometre Taşı',
    'totalUnassignedTicket' => 'Toplam Atanmamış Bilet',
    'typeWiseTicket' => 'Bilge Bilet yazın',
    'statusWiseTicket' => 'Durum Bilge Bileti',
    'channelWiseTicket' => 'Kanal Bilge Bileti',
  ),
  'client' =>
  array(
    'createTitle' => 'Müvekkil Bilgisi Ekle',
    'companyDetails' => 'Şirket Detayları',
    'clientOtherDetails' => 'Diğer Müvekkil Detayları',
    'companyName' => 'Şirket Adı',
    'website' => 'İnternet sitesi',
    'address' => 'Adres',
    'clientDetails' => 'Müvekkil Detayları',
    'clientName' => 'Müvekkil Adı',
    'clientEmail' => 'Müvekkil E-postası',
    'emailNote' => 'Müvekkil bu e-postayı kullanarak giriş yapacak.',
    'password' => 'Parola',
    'passwordNote' => 'Müvekkil bu şifreyi kullanarak giriş yapacak.',
    'passwordUpdateNote' => 'Müvekkil bu şifreyi kullanarak giriş yapacaktır. (Geçerli şifreyi saklamak için boş bırakın)',
    'mobile' => 'Mobil',
    'updateTitle' => 'Müvekkil Bilgilerini Güncelle',
    'addNewClient' => 'Yeni Müvekkil Ekle',
    'viewDetails' => 'Detayları göster',
    'projectName' => 'Project Name',
    'startedOn' => 'Başladı',
    'deadline' => 'Son teslim tarihi',
    'generateRandomPassword' => 'Rastgele Parola Oluştur',
    'offline' => 'Çevrim dışı',
    'online' => 'Çevrim içi',
    'all' => 'Her şey',
    'sendCredentials' => 'Kimlik Bilgilerini Gönder',
    'sendCredentialsMessage' => 'Müvekkile E-posta yoluyla kimlik bilgilerini göndermek istiyor musunuz?',
    'clientCategory'=>'Müvekkil Kategorisi',
    'clientSubCategory' => 'Müvekkil Alt Kategorisi',
    'clientBasicDetails' => 'Müvekkil Temel Ayrıntıları',
    'assignProject' => 'Assign Project',
    'cell' => 'Cell',
    'officePhoneNumber' => 'Ofis Telefon Numarası',
  ),
  'gdpr' =>
  array(
    'gdpr' => 'GDPR',
    'customers' => 'Customers',
    'purpose' => 'Amaç',
    'ipAddress' => 'IP Adresi',
    'staffMember' => 'Personel',
    'additionalDescription' => 'Ek açıklama',
    'purposeDescription' => 'Purpose Description',
    'optIn' => 'OPT IN',
    'optOut' => 'OPT OUT',
    'consent' => 'İzin ver',
    'requestDataRemoval' => 'Veri Taşıma İsteği',
    'requestAccountRemoval'=>'Hesabın kaldırılması talebi',
    'dataRemovalDescription' => 'Verilerin kaldırılmasının amacını kısaca açıklayın',
    'accountRemovalDescription'=>'Hesabın kaldırılmasının amacını kısaca açıklayın',
    'removalRequestSuccess' => 'Yöneticiye kaldırma isteği gönderildi. Onaylandıktan sonra bilgilendirileceksiniz.',
    'generalGdprSetting' => 'Genel GDPR Ayarları',
    'showGdprLink' => 'Show GDPR link in customers area navigation',
    'showGdprLinkFooter' => 'Show GDPR link in customers area footer',
    'showGdprLinkBlock' => 'GDPR page top information block',
    'enableConsentForCustomers' => 'Müşteriler için onayı etkinleştirin',
    'enableConsentForLeads' => 'Potansiyel Müşteriler için onayı etkinleştirin',
    'publicPageConsentInformationBlock' => 'Public page consent information block',
    'purposeOfConsent' => 'Purpose of consent',
    'addNewConsent' => 'Yeni izin ekle',
    'newConsentPurpose' => 'Yeni izin amacı',
    'rightOfAccess' => 'Erişim hakkı',
    'allowLead' => 'Müşteri adaylarının verilerini herkese açık formdan güncellemesine izin ver',
    'rightToDataProtability' => 'Veri Taşınabilirliği Hakkı',
    'enableCustomerExport' => 'Müşterilerin verilerini dışa aktarmalarını sağlayın',
    'rightToErasure' => 'Right to erasure',
    'enableCustomersToRequestToRemoveData' => 'Enable customers to request to remove data',
    'rightToInform' => 'Right to be informed',
    'enableTerm' => 'Enable Terms & Conditions customers footer',
    'termsCondition'=>'Şartlar ve koşullar',
    'privacyPolicy'=>'Gizlilik ve politika',
    'leadsToErasure'=>'Silinmeye yol açar',
    'enableLeadRequest'=>'Veri kaldırma talebinde bulunmak için müvekkil adayını etkinleştirin (genel form aracılığıyla)',
    'removalRequest'=>'Kaldırma İstekleri',
    'rightOfAccessRectification'=>'Erişim hakkı/Düzeltme hakkı',
    'termCondition' => 'Şartlar ve koşullar',
    'editInformation' =>'Bilgilerimi düzenle',
    'requestDataRemove'=>'Veri kaldırma talebinde bulunun',
    'exportData'=>'Verilerimi dışa aktar',
    'disagree'=>'Katılmıyorum',
    'agree'=>'Katılıyorum',
    'consentForLead'=>'Bu müvekkil adayı için izin yok.',
    'lastUpdate'=>'Son güncelleme',
    'noConsent'=>'İzin yok.',

  ),
  'contacts' =>
  array(
    'addContact' => 'Kişi ekle',
    'contactName' => 'Kişi adı',
  ),
  'notes'=>
  array(
    'notesTitle'=> 'Not Başlığı',
    'notesType'=>'Not Türü',
    'public'=> 'halka açık',
    'private' => 'Özel',
    'selectMember' =>'Üye',
    'client' => 'Müvekkil',
    'notesDetails' => 'Not Ayrıntıları',
    'addNotes' => 'Not ekle',
    'askReenterPassword' => 'Şifreyi yeniden girmeyi isteyin',
    'showClient'=> 'Is client show',
    'enterPassword' => 'Parolanı Gir',
  ),
  'employees' =>
  array(
    'addNewEmployee' => 'Yeni Çalışan Ekle',
    'editEmployee' => 'Çalışanı Düzenle',
    'createTitle' => 'Çalışan Bilgisi Ekle',
    'employeeName' => 'Çalışan Adı',
    'employeeEmail' => 'Çalışan E-postası',
    'emailNote' => 'Çalışan bu e-postayı kullanarak giriş yapacak.',
    'employeePassword' => 'Parola',
    'passwordNote' => 'Çalışan bu şifreyi kullanarak giriş yapacaktır.',
    'jobTitle' => 'İş ismi',
    'hourlyRate' => 'Saatlik ücret',
    'updateTitle' => 'Çalışan Bilgilerini Güncelle',
    'updatePasswordNote' => 'Çalışan bu şifreyi kullanarak giriş yapacaktır. (Geçerli şifreyi saklamak için boş bırakın)',
    'updateAdminPasswordNote' => 'Yönetici bu şifreyi kullanarak giriş yapacaktır. (Geçerli şifreyi saklamak için boş bırakın)',
    'tasksDone' => 'Tamamlanan Görevler',
    'hoursLogged' => 'Günlüğe Kaydedilen Saatler',
    'activity' => 'Aktivite',
    'profile' => 'Profil',
    'fullName' => 'Ad Soyad',
    'startTime' => 'Başlangıç Saati',
    'endTime' => 'Bitiş Zamanı',
    'totalHours' => 'Toplam Saat',
    'memo' => 'not',
    'slackUsername' => 'Slack Kullanıcı Adı',
    'joiningDate' => 'Katılma Tarihi',
    'gender' => 'Cinsiyet',
    'title' => 'Çalışan Seç',
    'role' => 'Rol',
    'lastDate' => 'Çıkış Tarihi',
    'employeeId' => 'Çalışan ID',
    'employeeIdInfo' => 'Çalışan ID çalışanlara dağıtılan benzersiz kimliktir.',
    'chooseDepartment' => 'Departman Seçin',
    'chooseDesignation' => 'Tanımlama Seçin',
    'chooseStatus' => 'Durum Seç',
    'pendingTasks' => 'Bekleyen görevler',
    'leavesTaken' => 'Leaves Taken',
    'department' => 'Bölüm',
    'designation' => 'Designation',
    'status' => 'Status',
  ),
  'projects' =>
  array(
    'addNewProject' => 'Yeni Proje Ekle',
    'projectDetails' => 'Proje Detayları',
    'noClientFound' => 'Müvekkil Bulunamadı',
    'projectName' => 'Proje Adı',
    'projectMembers' => 'Proje Üyeleri',
    'createTitle' => 'Proje Ekle',
    'selectClient' => 'Müvekkil Seç',
    'startDate' => 'Başlangıç Tarihi',
    'deadline' => 'Son Teslim Tarihi',
    'projectSummary' => 'Proje Özeti',
    'note' => 'Not',
    'updateTitle' => 'Proje Ayrıntılarını Güncelle',
    'projectCategory' => 'Proje Kategorisi',
    'clientFeedback' => 'Müvekkil Geribildirimi',
    'projectCompletionStatus' => 'Proje Tamamlama Durumu',
    'overview' => 'Genel Bakış',
    'members' => 'Üyeler',
    'files' => 'Dosyalar',
    'activeTimers' => 'Aktif Zamanlayıcılar',
    'whoWorking' => 'Who\'s Working',
    'activeSince' => 'Aktif Olduğu Tarih',
    'openTasks' => 'Açık Görevler',
    'daysLeft' => 'Kalan Günler',
    'hoursLogged' => 'Günlüğe Kaydedilen Saatler',
    'issuesPending' => 'Bekleyen Sorunlar',
    'activityTimeline' => 'Etkinlik Zaman Çizelgesi',
    'addMemberTitle' => 'Proje Üyeleri Ekle',
    'uploadFile' => 'Dosya yükleme',
    'dropFile' => 'Dosyaları buraya bırakın veya yüklemek için tıklayın',
    'projectUpdated' => ' proje detayları güncellendi.',
    'noOpenTasks' => 'Açık görev yok.',
    'calculateTasksProgress' => 'Görevler aracılığıyla ilerlemeyi hesaplayın',
    'viewGanttChart' => 'Gantt Chart',
    'clientViewTask' => 'Müvekkil bu projenin görevlerini yönetebilir',
    'manualTimelog' => 'Manuel zaman günlüklerine izin verilsin mi?',
    'clientTaskNotification' => 'Müvekkile görev bildirimi gönderilsin mi?',
    'allProject' => 'Tüm Projeler',
    'withoutDeadline' => 'Son teslim tarihi olmadan',
    'expenses_total' => 'Masraflar',
    'projectExpenseInfo' => 'Giderler Modülünden Hesaplanan',
    'projectEarningInfo' => 'Ödemeler Modülünden Hesaplanan',
    'selfAssignAsProjectMember' => 'Proje üyesi olarak kendi kendine atama',
    'addFileLink' => 'Dosya bağlantısı ekle',
    'milestones' => 'Milestones',
    'milestoneCost' => 'Milestone Cost',
    'createMilestone' => 'Create Milestone',
    'milestoneSummary' => 'Milestone Summary',
    'milestoneTitle' => 'Milestone Title',
    'resume' => 'Devam et',
    'pause' => 'Duraklat',
    'projectBudget' => 'Proje bütçesi',
    'hours_allocated' => 'Ayrılan Saatler',
    'budgetInfo' => 'Bütçe Bilgileri',
    'remindBefore' => 'Önce Hatırlat',
    'viewPublicGanttChart' => 'Public Gantt Chart',
    'burndownChart' => 'Açılış tablosu',
    'fileName' => 'Dosya adı',
    'discussion' => 'Görüşme',
    'projectInfo' => 'Proje Bilgileri',
    'clientInfo' => 'Müvekkil Bilgileri',
    'addCostProjectBudget' => 'Proje Bütçesine Maliyet Ekle',
    'hideFinishedProjects' => 'Biten Projeleri Gizle',
    'otherInfo' => 'Diğer Bilgiler',
    'notes'=>'Notlar',
    'viewProjectDetails' => 'Proje Detaylarını Görüntüle',
  ),
  'tasks' =>
  array(
    'newTask' => 'Yeni görev',
    'showAll' => 'Hepsini Göster',
    'selectProject' => 'Proje Seç',
    'hideCompletedTask' => 'Tamamlanan görevi gizle',
    'myTask' => 'Benim görevim',
    'changeStatus' => 'Görevi Değiştir',
    'dueDate' => 'Bitiş tarihi',
    'selectPriority' => 'Öncelik Seç',
    'boardColumn' => 'Pano Sütunu',
    'users' => 'Kullanıcılar',
    'selectTaskCategory' => 'Görev kategorisini seçin',
    'noTaskCategory' => 'Görev kategorisi yok',
    'moveToBoard' => 'Panoya Taşı',
    'lastCreated' => 'Son Oluşturulan',
    'dueSoon' => 'Yakında Teslim',
    'assignTo' => 'Atandı',
    'high' => 'Yüksek',
    'medium' => 'Orta',
    'low' => 'Düşük',
    'priority' => 'Öncelik',
    'updateTask' => 'Görevi Güncelle',
    'chooseAssignee' => 'Atanan Seç',
    'taskDetail' => 'Görev Detayı',
    'taskBoard' => 'Görev Panosu',
    'addBoardColumn' => 'Sütun Ekle',
    'columnName' => 'Sütun adı',
    'labelColor' => 'Etiket Rengi',
    'tasksTable' => 'Görevler Tablosu',
    'position' => 'Position',
    'subTask' => 'Alt Görev',
    'comment' => 'Yorum Yap',
    'taskCategory' => 'Görev Kategorisi',
    'category' => 'Kategori',
    'assignBy' => 'Atanmak',
    'markComplete' => 'Tamamlandı olarak işaretle',
    'markIncomplete' => 'Eksik olarak işaretle',
    'reminder' => 'Hatırlatma',
    'cyclesToolTip' => 'Aşağıdaki döngü sayısı için başlangıç ve bitiş tarihi arasında yinelenen görev oluşturulacaktır.',
    'deleteRecurringTasks' => 'Yinelenen görevlerle silin.',
    'uplodedFiles' => 'Yüklenmiş dosyalar',
    'dependent' => 'Task is dependent on another task',
    'dependentTask' => 'Dependent Task',
    'chooseTask' => 'Görev Seç',
    'preDeadlineReminder' => 'Önceden görev hatırlatıcısı gönder',
    'onDeadlineReminder' => 'Son teslim gününde görev hatırlatıcısı gönder',
    'postDeadlineReminder' => 'Sonrasında görev hatırlatıcısı gönder:',
    'makePrivate' => 'Özel Yap',
    'privateInfo' => 'Özel görevler yalnızca yönetici, atanan tarafından görülebilir.',
    'createActivity' => 'Görev tarafından oluşturulur',
    'updateActivity' => 'Görev ayrıntıları tarafından güncellenir ',
    'statusActivity' => 'Görev durumu tarafından değiştirildi ',
    'commentActivity' => 'Yorum ekleyen ',
    'fileActivity' => 'Dosya tarafından yüklendi ',
    'subTaskCreateActivity' => 'Alt görev tarafından oluşturulur ',
    'subTaskUpdateActivity' => 'Alt görev tarafından güncellenir ',
    'history' => 'Tarih',
    'defaultTaskStatus' => 'Varsayılan Görev Durumu',
    'billable' => 'Faturalandırılabilir',
    'billableInfo' => 'Bu görevin zaman kaydı için fatura oluşturulabilir.',
    'assigned' => 'Atandı',
    'taskLabel' => 'Görev Etiketi',
    'setTimeEstimate' => 'Zaman tahminini ayarla',
      'noSubTaskFound' => 'Alt Görev Bulunamadı',
  ),
  'invoices' =>
  array(
    'addInvoice' => 'Fatura Ekle',
    'paid' => 'Ücretli',
    'unpaid' => 'Ücretsiz',
    'currency' => 'Para birimi',
    'invoiceDate' => 'Fatura tarihi',
    'item' => 'Öğe',
    'qty' => 'Qty/Hrs',
    'unitPrice' => 'Birim fiyat',
    'amount' => 'Miktar',
    'addItem' => 'Öğe Ekle',
    'subTotal' => 'Ara toplam',
    'discount' => 'İndirim',
    'tax' => 'Vergi',
    'total' => 'Toplam',
    'billedTo' => 'Fatura',
    'generatedBy' => 'Oluşturan',
    'price' => 'Fiyat',
    'type' => 'Tür',
    'payPaypal' => 'Paypal ile ödeme',
    'payPaystack' => 'Paystack ile ödeme',
    'downloadPdf' => 'PDF İndir',
    'isRecurringPayment' => 'Yinelenen bir ödeme mi?',
    'billingCycle' => 'Fatura döngüsü',
    'billingFrequency' => 'Faturalandırma Sıklığı',
    'billingInterval' => 'Faturalandırma Aralığı',
    'recurringPayments' => 'Yinelenen ödeme',
    'payNow' => 'Şimdi Öde',
    'payStripe' => 'Stripe ile ödeme',
    'taxName' => 'Vergi Adı',
    'rate' => 'Rate',
    'payOffline' => 'Çevrimdışı Öde',
    'partial' => 'Kısmen ödenmiş',
    'due' => 'Due',
    'uploadInvoice' => 'Fatura Yükle',
    'project' => 'Proje',
    'copyPaymentLink' => 'Ödeme Bağlantısını Kopyala',
    'payRazorpay' => 'Razorpay ile ödeme',
    'appliedCredits' => 'Uygulanan Krediler',
    'amountDue' => 'Alacak miktarı',
    'amountPaid' => 'Ödenen miktar',
    'review' => 'Gözden Geçir',
    'OfflinePaymentRequest' => 'Çevrimdışı Ödeme Talebi',
    'paymentGateway' => 'Payment Gateway',
    'transactionID' => 'İşlem Kimliği',
    'remark' => 'Açıklama',
    'paymentDetails' => 'Ödeme detayları',
    'paidOn' => 'Ödeme Tarihi',
    'showShippingAddress' => 'Gönderim Adresini Göster',
    'showShippingAddressInfo' => 'Faturalarda Gönderi Adresini göster, görünümü ve pdf dosyalarını göster',
    'markCancel' => 'Mark Cancel',
    'notSent' => 'Gönderilmedi',
    'draft' => 'Taslak',
    'mollie' => 'Mollie ile ödeme',
    'buy' => 'Satın Al',
    'authorize' => 'Pay via Authorize',
    'projectWithClient' => 'Müvekkili olan projeler',
    'dueDate' => 'Bitiş Tarihi',
    'totalUnpaidInvoice' => 'Toplam Ödenmemiş Faturalar',
    'noInvoiceForClient'=>'Bu müvekkil için fatura yok.',
    'to'=>'için',
    'paymentMethod'=>'Ödeme şekli',
    'recentPayments'=>'Son Ödemeler',
    'invoiceNumber'=>'Fatura numarası',
    'hsnSacCode'=> 'Hsn/Sac',
  ),
  'issues' =>
  array(
    'pending' => 'Bekliyor',
    'addIssue' => 'Sorun Ekle',
    'updateIssue' => 'Güncelleme Sorunu',
    'resolved' => 'Çözüldü',
    'markPending' => 'Beklemede Olarak İşaretle',
    'markResolved' => 'Çözüldü Olarak İşaretle',
    'reportedOn' => 'Rapor Tarihi',
  ),
  'timeLogs' =>
  array(
    'whoLogged' => 'Kim Giriş Yaptı',
    'startTime' => 'Başlangıç saati',
    'endTime' => 'Bitiş zamanı',
    'totalHours' => 'Toplam Saat',
    'memo' => 'Not',
    'lastUpdatedBy' => 'Son güncelleyen',
    'employeeName' => 'Çalışan Adı',
    'startDate' => 'Başlangıç tarihi',
    'endDate' => 'Bitiş tarihi',
    'logTime' => 'Günlük Süresi',
    'startTimer' => 'Zamanlayıcıyı Başlat',
    'stopTimer' => 'Zamanlayıcıyı Durdur',
    'selectProject' => 'Proje Seç',
    'selectTask' => 'Görev Seç',
    'noTaskFound' => 'Görev Atanmadı',
    'noProjectFound' => 'Görev Atanmadı',
    'task' => 'Görev',
    'NotHaveAccessOFTaskModule' => 'Görev modülleri etkin değil. Görev modülünü etkinleştirmek için lütfen yönetici ile iletişime geçin',
  ),
  'taskCalendar' =>
  array(
    'note' => 'Takvim, teslim edilen görevleri son tarihlerinde gösterir.',
    'taskDetail' => 'Görev Detayı',
  ),
  'notices' =>
  array(
    'addNotice' => 'Yeni Bildirim Ekle',
    'notice' => 'Bildirim',
    'noticeHeading' => 'Bildirim Başlığı',
    'noticeDetails' => 'Bildirim Ayrıntıları',
    'updateNotice' => 'Güncelleme Bildirimi',
    'toEmployee' => 'Çalışanlara',
    'toClients' => 'Müvekkillere',
  ),
  'sticky' =>
  array(
    'addNote' => 'Not ekle',
    'lastUpdated' => 'Güncellenmiş',
    'colors' => 'Renk',
  ),
  'taskReport' =>
  array(
    'taskToComplete' => 'Toplam Görevler',
    'completedTasks' => 'Tamamlanmış Görevler',
    'pendingTasks' => 'Bekleyen görevler',
    'chartTitle' => 'Pie Chart',
  ),
  'leaveReport' =>
  array(
    'leaveReport' => 'Rapordan Ayrıl',
  ),
  'timeLogReport' =>
  array(
    'chartTitle' => 'Zaman Günlüğü Çubuğu Grafiği',
  ),
  'financeReport' =>
  array(
    'showAmountIn' => 'Tutarı şurada göster: ',
    'selectCurrency' => 'Para birimini seçin',
    'chartTitle' => 'Kazanç Çubuğu Grafiği',
    'financeReport' => 'Kazanç Çubuğu Grafiği',
    'noteText' => 'Ücretler, farklı para birimleri için en son döviz kuru ile hesaplanır.',
  ),
  'accountSettings' =>
  array(
    'updateTitle' => 'Kurulum Ayarlarını Güncelle',
    'companyName' => 'Şirket Adı',
    'companyEmail' => 'Şirket E-postası',
    'companyPhone' => 'Şirket Telefonu',
    'companyWebsite' => 'Şirket Web Sitesi',
    'companyLogo' => 'Logo',
    'companyAddress' => 'Şirket Adresi',
    'defaultTimezone' => 'Varsayılan Saat Dilimi',
    'defaultCurrency' => 'Varsayılan Para Birimi',
    'changeLanguage' => 'Dili değiştir',
    'uploadLogo' => 'Logonuzu yükleyin',
    'getLocation' => 'Geçerli konumu ayarla',
    'dateFormat' => 'Tarih formatı',
    'timeFormat' => 'Zaman formatı',
    'google_map_key' => 'Google harita anahtarı',
    'currencyConverterKey' => 'Para birimi dönüştürücü anahtarı',
    'google_recaptcha_key' => 'Google Recaptcha Key',
    'sendReminder' => 'Hatırlatıcıyı gönder',
    'sendReminderInfo' => 'Proje üyelerine projelerin teslim tarihini hatırlatın.',
    'google_recaptcha_secret' => 'Google Recaptcha Secret',
    'weekStartFrom' => 'Hafta başlangıcı',
    'updateEnableDisableTest' => 'Uygulama güncelleme ayarını etkinleştirin/devre dışı bırakın.',
    'updateEnableDisable' => 'Uygulama Güncellemesi',
    'emailVerification' => 'E-posta Doğrulama',
    'emailVerificationEnableDisable' => 'Yeni kayıtlı şirketlerin e-posta doğrulamasını etkinleştirin/devre dışı bırakın.',
    'frontLogo' => 'Ön Logo',
    'htmlOrEmbeded' => 'İletişim sayfası için Html/Embed',
    'enableGoogleRecaptcha' => 'Enable Google Recaptcha',
    'googleRecaptchaMessage' => 'Google Recaptcha will be enabled for contact us, login and signup',
    'appDebug' => 'Uygulama Hata Ayıklama',
    'enableRegister' => 'Kaydı Etkinleştir',
    'appDebugInfo' => 'Uygulama hata ayıklama ayarını etkinleştirin/devre dışı bırakın.',
    'enableregisterInfo' => 'Kaydı Etkinleştir/Devre Dışı Bırak.',
    'expiredMessage'=>'Lisans Süresi Doldu Mesajı',
    'faviconImage'=>'Favicon Resmi',
    'showDashboardClock' => 'Pano Saatini Göster',
    'dashboardClock' => 'Pano Saati'
  ),
  'profile' =>
  array(
    'updateTitle' => 'Profil Bilgilerini Güncelle',
    'yourName' => 'Adınız',
    'yourEmail' => 'E-posta adresiniz',
    'yourPassword' => 'Şifreniz',
    'passwordNote' => 'Mevcut şifrenizi korumak için boş bırakın.',
    'yourMobileNumber' => 'Telefon Numaranız',
    'yourAddress' => 'Adresiniz',
    'profilePicture' => 'Profil Fotoğrafı',
    'uploadPicture' => 'Resminizi yükleyin',
  ),
  'emailSettings' =>
  array(
    'notificationTitle' => 'E-posta Bildirim Ayarlarını Yapın',
    'notificationSubtitle' => 'Kullanıcıya e-posta gönderilmesi gereken durumları seçin.',
    'configTitle' => 'Mail Yapılandırması',
    'mailDriver' => 'Mail Sürücüsü',
    'mailHost' => 'Mail Host',
    'mailPort' => 'Mail Girişi',
    'mailUsername' => 'Mail Kullanıcı Adı',
    'mailPassword' => 'Mail Parolası',
    'mailFrom' => 'İsimden Mail',
    'mailEncryption' => 'Mail Şifreleme ',
    'userRegistration' => 'Kullanıcı Kaydı/Yönetici Tarafından Eklendi',
    'employeeAssign' => 'Projeye Çalışan Ataması',
    'newNotice' => 'Yeni Bildirim Yayınlandı',
    'taskAssign' => 'Göreve Kullanıcı Ata',
    'expenseAdded' => 'Yeni Gider (Yönetici Tarafından Eklendi)',
    'expenseMember' => 'Yeni Harcama (Üye Tarafından Eklendi)',
    'expenseStatus' => 'Gider Durumu Değiştirildi',
    'ticketRequest' => 'Yeni Destek Bilet Talebi',
    'mailFromEmail' => 'E-postadan Posta',
    'leaveRequest' => 'İzin Talebi Alındı',
    'taskComplete' => 'Görev tamamlandı',
    'sendTestEmail' => 'Test E-postası Gönder',
    'removeImage' => 'Resmi Kaldır',
    'invoiceNotification' => 'Fatura Bildirimi',
    'emailNotifications' => 'E-posta Bildirimleri',
  ),
  'moduleSettings' =>
  array(
    'employeeModuleTitle' => 'Modüller',
    'clientModuleTitle' => 'Müvekkil Modülü Başlığı',
    'employeeSubTitle' => 'Etkinleştirmek istediğiniz modülleri seçin.',
    'clientSubTitle' => 'Müvekkilin erişebileceği modülleri seçin.',
    'moduleSetting' => 'Modül Ayarı',
    'section' => 'Bölüm.',
  ),
  'currencySettings' =>
  array(
    'addNewCurrency' => 'Yeni Para Birimi Ekle',
    'currencyName' => 'Para Birimi Adı',
    'currencySymbol' => 'Para Birimi Sembolü',
    'currencyCode' => 'Para Birimi Kodu',
    'currencies' => 'Para Birimleri',
    'updateTitle' => 'Para Birimi Güncelle',
    'exchangeRate' => 'Döviz kuru',
    'cantDeleteDefault' => 'Varsayılan para birimi silinemez.',
    'isCryptoCurrency' => 'Kripto para birimi',
    'usdPrice' => 'ABD Doları Fiyatı',
    'usdPriceInfo' => 'Kazanç hesaplamak için gereklidir.',
    'currencyPosition' => 'Para Birimi Pozisyonu',
    'front' => 'Ön',
    'behind' => 'Arkada',
    'example' => 'Örnek',
  ),
  'messages' =>
  array(
    'startConversation' => 'Konuşmayı Başlat',
    'chooseMember' => 'Üye Seç',
    'message' => 'Mesaj',
    'send' => 'Gönder',
    'searchContact' => 'Kişi Ara',
    'typeMessage' => 'Mesajınızı buraya yazınız...',
    'chooseAdmin' => 'Yönetici Seç',
    'chooseDepartment' => 'Departman Seçin',
    'allowClientEmployeeChat' => 'Müvekkil ve çalışanlar arasında sohbete izin verilsin mi?',
    'allowClientAdminChat' => 'İstemci ve yönetici arasında sohbete izin verilsin mi?',
    'admins' => 'Yöneticiler',
    'members' => 'Proje Üyeleri',
  ),
  'taskDetail' => 'Görev Detayı',
  'projectCategory' =>
  array(
    'addProjectCategory' => 'Proje Kategorisi Ekle',
    'categoryName' => 'Kategori adı',
  ),
  'themeSettings' =>
  array(
    'adminPanelTheme' => 'Yönetici Paneli Teması',
    'projectAdminPanelTheme' => 'Proje Yönetici Paneli Teması',
    'employeePanelTheme' => 'Çalışan Paneli Teması',
    'clientPanelTheme' => 'Müvekkil Paneli Teması',
    'headerColor' => 'İkincil renk',
    'sidebarColor' => 'Kenar Çubuğu Rengi',
    'sidebarTextColor' => 'Kenar Çubuğu Metin Rengi',
    'linkColor' => 'Bağlantı rengi',
    'loginScreenBackground' => 'Giriş Ekranı Arka Planı',
    'uploadImage' => 'Fotoğraf yükleniyor',
    'customCss' => 'Özel CSS',
    'useDefaultTheme' => 'Varsayılan Temayı Kullan',
    'useCustomTheme' => 'Özel Tema Kullan',
    'enableRoundTheme' => 'Enable rounded theme?',
    'customCssNote' => 'Geniş özel css´niz varsa, <strong>public/css/</strong> içinde aşağıdaki 3 dosyayı oluşturun ve üzerinde değişiklik yapın.',
    'publicCss' => 'public/css/',
    'customCssPlaceholder' => 'Bu satırdan sonra özel css´nizi girin',
    'superAdminPanelTheme' => 'Süper Yönetici Paneli Teması',
  ),
  'estimates' =>
  array(
    'createEstimate' => 'Tahmin Oluştur',
    'validTill' => 'Kadar geçerli',
    'waiting' => 'Beklemek',
    'accepted' => 'Kabul edildi',
    'declined' => 'Reddedildi',
    'updateEstimate' => 'Tahmini Güncelle',
    'convertEstimateTitle' => 'Tahmini Faturaya Dönüştür',
    'estimatesNumber' => 'Tahmin #',
    'convertInvoiceTitle' => 'FATURAYI KREDİYE DÖNÜŞTÜRMEK',
    'firstName' => 'Ad',
    'lastName' => 'Soyad',
    'signature' => 'İmza',
    'undo' => 'Geri alma',
    'clear' => 'Temiz',
    'signatureAndConfirmation' => 'İmza ve Kimlik Onayı',
    'duplicateEstimate' => 'Yinelenen Tahmin',
    'estimateTo' => 'Tahmini Hedef:',
    'createDate' => 'Oluşturma Tarihi:',
    'item' => 'Öğe',
    'price' => 'Fiyat',
    'qty' => 'Qty',
    'total' => 'Toplam',
    'address' => 'Adres:',
    'subtotal' => 'Ara toplam',
    'discount' => 'İndirim',
    'notes' => 'Notlar',
    'sendEstimate' => 'Tahmini Gönder',
    'estimateNumber' => 'Tahmin Sayısı',
    'invoiveTerms' => 'Fatura Koşulları',
  ),
  'payments' =>
  array(
    'addPayment' => 'Ödeme Ekle',
    'paidOn' => 'Ödeme Tarihi',
    'selectInvoice' => 'Fatura Seç',
    'paymentGateway' => 'Ödeme Sağlayıcı',
    'transactionId' => 'İşlem Kimliği',
    'updatePayment' => 'Ödemeyi Güncelle',
    'paypalStatus' => 'Paypal Durumu',
    'markInvoicePaid' => 'Fatura Ödendi Olarak İşaretle?',
    'stripeStatus' => 'Stripe Status',
    'import' => 'CSV´yi içe aktar',
    'firstCharacter' => 'İlk Karakter Para Birimi mi?',
    'remark' => 'Açıklama',
    'amount' => 'Miktar',
    'totalAmount' => 'Toplam tutar',
    'totalPaid' => 'Toplam Ödenen',
    'totalDue' => 'Toplam Vade',
    'paymentDetailNotFound' => 'Ödeme ayrıntıları bulunamadı.',
    'paymentDetails' => 'Ödeme Detayları',
    'paymentLink' => 'Ödeme Bağlantısı',
    'razorpayStatus' => 'Razorpay Durumu',
    'choosePlan' => 'Planı Seç',
    'choosePaymentMethod' => 'Ödeme Yöntemini Seçin',
  ),
  'expenses' =>
  array(
    'addExpense' => 'Gider Ekle',
    'itemName' => 'Öğe adı',
    'purchaseDate' => 'Satın alma tarihi',
    'purchaseFrom' => 'den satın alındı',
    'updateExpense' => 'Gider Güncelle',
    'infinite' => 'Sayısız Masraflar için',
    'expenseCategory' => 'Gider Kategorisi',
    'editExpense' => 'Gideri Düzenle',
    'attachBill' => 'Fatura Ekle',
    'removeBill' => 'Faturayı Kaldır',

  ),
  'mobile' =>
  array(
    'camera' => 'Kamera',
    'gallery' => 'Galeri',
    'maximumFileSize' => 'Maksimum Dosya Boyutu',

  ),
  'expensesRecurring' =>
  array(
    'addExpense' => 'Yinelenen Gider Ekle',
    'itemName' => 'Öğe Adı',
    'purchaseDate' => 'Satın alma tarihi',
    'purchaseFrom' => 'den satın alındı',
    'updateExpense' => 'Sayısız Faturalar için',
    'infinite' => 'Sayısız Faturalar için',
    'created_at' => 'Oluşturma Tarihi',
    'dayOfWeek' => 'Haftanın günü',
    'dayOfMonth' => 'Ayın günü',
    'lastPaymentDate' => 'Son Ödeme Tarihi',
  ),
  'invoiceSettings' =>
  array(
    'invoicePrefix' => 'Fatura Ön Eki',
    'template' => 'Şablon',
    'dueAfter' => 'Due after',
    'invoiceTerms' => 'Fatura Şartları',
    'estimateTerms' => 'Tahmini Terimler',
    'updateTitle' => 'Finans Ayarlarını Güncelle',
    'invoiceDigit' => 'Fatura Numarası Rakamları',
    'invoiceLookLike' => 'Fatura Numarası Örneği',
    'estimatePrefix' => 'Tahmin Ön Eki',
    'estimateDigit' => 'Sayı Basamağını Tahmin Et',
    'estimateLookLike' => 'Tahmin Sayısı Örneği',
    'credit_notePrefix' => 'Kredi Notu Ön Eki',
    'credit_noteDigit' => 'Kredi Notu Rakamları',
    'credit_noteLookLike' => 'Kredi Notu Numarası Örneği',
    'logo' => 'fatura logosu',
  ),
  'slackSettings' =>
  array(
    'updateTitle' => 'Slack Ayarlarını Güncelle',
    'uploadSlackLogo' => 'Bildirim Logosunu Yükle',
    'notificationTitle' => 'Bildirim Ayarlarını Belirle',
    'notificationSubtitle' => 'Kullanıcıya bir bildirim gönderilmesi gereken olayları seçin.',
    'sendTestNotification' => 'Test Bildirimi Gönder',
    'slackWebhook' => 'Slack Webhook',
    'slackNotificationLogo' => 'Bildirim Logosu',
  ),
  'update' =>
  array(
    'systemDetails' => 'Sistem Ayrıntıları',
    'updateTitle' => 'Yeni Sürüme Güncelle',
    'updateDatabase' => 'Veri Tabanını Güncelle',
    'fileReplaceAlert' => 'Çalışma paketini yeni sürüme güncellemek için talimatlar için belgeleri kontrol edin.',
    'updateDatabaseButton' => 'Veritabanını güncellemek için tıklayın',
    'newUpdate' => 'Yeni güncelleme mevcut',
    'updateNow' => 'Şimdi Güncelle',
    'updateAlternate' => 'Şimdi Güncelle düğmesi çalışmıyorsa, belgelerde belirtilen güncelleme talimatlarını izleyin.',
    'updateManual' => 'Alternatif Yöntemi Güncelle',
    'updateFiles' => 'Dosyaları Güncelle',
    'downloadUpdateFile' => 'Güncelleme Dosyasını İndir',
    'install' => 'Yüklemek',
    'moduleFile' => 'Modül zip dosyası',
  ),
  'incomeVsExpenseReport' =>
  array(
    'totalIncome' => 'Toplam gelir',
    'totalExpense' => 'Toplam Gider',
    'chartTitle' => 'Grafik çubuğu',
  ),
  'tickets' =>
  array(
    'agents' => 'Temsilciler',
    'chooseAgents' => 'Temsilcileri Seçin',
    'assignGroup' => 'Grup Ata',
    'addGroup' => 'Grup ekle',
    'group' => 'Grup',
    'manageGroups' => 'Grupları Yönet',
    'groupName' => 'Grup İsmi',
    'ticketType' => 'Ticket Type',
    'addType' => 'Tip Ekle',
    'channelName' => 'Kanal İsmi',
    'template' => 'Şablon',
    'templateHeading' => 'Şablon Başlığı',
    'templateText' => 'Şablon Metni',
    'addTicket' => 'Create Ticket',
    'ticket' => 'Ticket',
    'ticketSubject' => 'Ticket Subject',
    'ticketDescription' => 'Ticket Description',
    'applyTemplate' => 'Şablonu Uygula',
    'agent' => 'Temsilci',
    'tags' => 'Etiketler',
    'addChannel' => 'Kanal Ekle',
    'requesterName' => 'İsteyenin Adı',
    'reply' => 'Yanıtla',
    'totalTickets' => 'Total Tickets',
    'totalClosedTickets' => 'Closed Tickets',
    'totalOpenTickets' => 'Open Tickets',
    'totalPendingTickets' => 'Pending Tickets',
    'totalResolvedTickets' => 'Resolved Tickets',
    'requestedOn' => 'Talep Tarihi',
    'requestTicket' => 'New Support Ticket',
    'closeTicket' => 'Close Ticket',
    'goToAgentDashboard' => 'Temsilci Kontrol Paneline Git',
    'reopenTicket' => 'Reopen Ticket',
    'totalTicketInfo' => 'No. of new tickets which were created for the selected date range.',
    'closedTicketInfo' => 'No. of tickets which were closed in the selected date range.',
    'openTicketInfo' => 'No. of tickets which are not yet assigned to any agent and updated in the selected date range.',
    'pendingTicketInfo' => 'No. of tickets which were updated in the selected date range and are assigned to an agent.',
    'resolvedTicketInfo' => 'No. of tickets which were resolved in the selected date range but waiting for requester confirmation.',
    'completedProjects' => 'Tamamlanmış Projeler',
    'inProcessProjects' => 'Devam Eden Projeler',
    'overDueProjects' => 'Gecikmiş Projeler',
    'totalUnresolvedTickets' => 'Unresolved Tickets',
    'ticketTrendGraph' => 'Ticket trend graph',
    'urgent' => 'Acil',
    'nofilter' => 'Filtresiz',
    'noGroupAssigned' => 'Grup atanmadı',
    'submitOpen' => 'Açık Olarak Gönder',
    'submitPending' => 'Beklemede Olarak Gönder',
    'submitResolved' => 'Çözümlenmiş Olarak Gönder',
    'submitClosed' => 'Kapalı Olarak Gönder',
    'ticketDetail' => 'Ticket Detail',
    'notAssigned' => 'Atanmadı',
    'priority' => 'Öncelik',
    'selectPriority' => 'Öncelik Seç',
    'newTicket' => 'New Ticket',
    'ticketChannel' => 'Ticket Channel',
    'requester' => 'Talep eden',
    'replies' => 'Cevaplar',
    'open' => 'Açık',
    'pending' => 'Bekliyor',
    'resolved' => 'Çözüldü',
    'closed' => 'Kapalı',
    'saveChanges'=>'Değişiklikleri Kaydet',
    'name'=>'Ad',
    'email'=>'Posta',
    'ticket_subject'=> 'Ticket Subject',
    'ticket_description'=> 'Mesajlar',
    'type'=> 'Tür',
    'message'=> 'Mesaj',
    'googleCaptcha'=> 'Google Captcha',
    'mobile_number' => 'Cep Numarası',
  ),
  'attendance' =>
  array(
    'officeStartTime' => 'Ofis Başlangıç Saati',
    'officeEndTime' => 'Ofis Bitiş Saati',
    'halfDayMarkTime' => 'HalfDay Mark Time',
    'lateMark' => 'Late mark after (minutes)',
    'allowSelfClock' => 'Allowed Employee self Clock-In/Clock-Out',
    'markAttendance' => 'Katılımı İşaretle',
    'clock_in' => 'İş başı yapmak',
    'late' => 'Geç',
    'clock_out' => 'Çıkış Saati',
    'halfDay' => 'Yarım gün',
    'working_from' => 'Çalışma',
    'officeOpenDays' => 'Ofis açılır',
    'totalWorkingDays' => 'Toplam Çalışma Günleri',
    'daysPresent' => 'Mevcut Günler',
    'absent' => 'Devamsız',
    'present' => 'Mevcut',
    'currentTime' => 'Şimdiki zaman',
    'attendanceByDate' => 'Tarihe Göre Katılım',
    'attendanceByMember' => 'Üye Katılımı',
    'holiday' => 'Tatil',
    'holidays' => 'Bayram',
    'holidayfor' => 'için tatil',
    'checkininday' => 'Bir günde izin verilen maksimum giriş?',
    'maxColckIn' => 'Maksimum check-in sayısına ulaşıldı.',
    'attendanceDetail' => 'Katılım Detayı',
    'yes' => 'Evet',
    'no' => 'Hayır',
    'leave' => 'İzinli',
    'leaveFor' => 'için ayrılmak',
    'checkForIp' => 'Eklenen IP adresi ile saat girişi kontrolü',
    'checkForRadius' => 'Eklenen konum Radius ile saat kontrolü',
    'radius' => 'Yarıçap (metre olarak)',
    'ipAddress' => 'IP Adresi',
    'hoursClocked' => 'Hours Clocked',
    'notClockOut' => 'Did not clock out',
    'everyonePresent' => 'Bugün herkes var',
    'clockedIn' => 'Clocked In',
    'clockedOut' => 'Clocked Out',
    'workFrom' => 'Ofis, Ev, vb.',
    'viewFullAttendance' => 'Tam Katılımı Görüntüle',
  ),
  'customFields' =>
  array(
    'label' => 'Etiket',
    'addField' => 'Alan ekle',
    'editField' => 'Alanı Düzenle',
  ),
  'events' =>
  array(
    'addEvent' => 'Etkinlik ekle',
    'eventName' => 'Etkinlik adı',
    'startOn' => 'Başlama Tarihi',
    'endOn' => 'Bitiş Tarihi',
    'addAttendees' => 'Katılımcı Ekle',
    'attendees'=> 'Katılımcılar',
    'allEmployees' => 'Tüm Çalışanlar',
    'where' => 'Nerede',
    'repeat' => 'Tekrar et',
    'repeatEvery' => 'Hep tekrarla',
    'cycles' => 'Döngüler',
    'cyclesToolTip' => 'Döngü sayısından sonra tekrarlama durdurulacaktır. Sonsuza kadar boş tutun.',
    'viewAttendees' => 'Katılımcıları Görüntüle',
    'attendees' => 'Katılımcılar',
    'addClients'=>'Müvekkil Ekle',
    'allClients' => 'Tüm Müvekkiller',
    'eventType' => 'Etkinlik tipi',
    'eventCategory' => 'Etkinlik Kategorisi',
    'viewClients' => 'Müvekkilleri Görüntüle',
  ),
  'payroll' =>
  array(
    'addPayroll' => 'Add Payroll',
    'amountPaid' => 'Ödenen miktar',
    'updatePayroll' => 'Update Payroll',
    'projectPayrollReport' => 'Project Payroll Report',
    'totalEarning' => 'Toplam Kazanç',
  ),
  'roles' =>
  array(
    'addRole' => 'Rolü Yönet',
  ),
  'permission' =>
  array(
    'projectNote' => 'Kullanıcı, kendisine atanan projelerin temel detaylarını herhangi bir izin almadan da görebilir.',
    'attendanceNote' => 'Kullanıcı herhangi bir izin almadan da kendi katılımını görebilir.',
    'taskNote' => 'Kullanıcı kendisine atanan görevleri izinsiz de görebilir.',
    'ticketNote' => 'Kullanıcı, kendisi tarafından oluşturulan biletleri herhangi bir izin olmadan da varsayılan olarak görüntüleyebilir.',
    'eventNote' => 'Kullanıcı, katılacağı etkinlikleri herhangi bir izin almadan da varsayılan olarak görüntüleyebilir.',
    'holidayNote' => 'Kullanıcı herhangi bir izin almadan tatilleri varsayılan olarak görebilir.',
    'selectAll' => 'Hepsini seç',
    'addRoleMember' => 'Üyelerin Rolünü Yönet',
    'addMembers' => 'Üye Ekle',
    'roleName' => 'Rol İsmi',
  ),
  'leaves' =>
  array(
    'assignLeave' => 'İzin Ata',
    'addLeaveType' => 'İzin Türü Ekle',
    'leaveType' => 'Leave Type',
    'selectDuration' => 'Süre Seç',
    'single' => 'Tekli',
    'multiple' => 'Çoklu',
    'halfDay' => 'Yarım gün',
    'hours' => 'Saatler',
    'selectDates' => 'Tarihleri Seçin',
    'reason' => 'Devamsızlık Nedeni',
    'applicantName' => 'Başvuranın ismi',
    'updateLeave' => 'İzin Güncelle',
    'pendingLeaves' => 'Pending Leaves',
    'applyLeave' => 'İzin Uygula',
    'noOfLeaves' => 'No of Leaves',
    'countLeavesFromDateOfJoining' => 'Count leaves from the date of joining',
    'countLeavesFromStartOfYear' => 'Count leaves from the start of the year',
    'leavesTaken' => 'Leaves Taken',
    'remainingLeaves' => 'Remaining Leaves',
    'myLeaves' => 'My Leaves',
    'leaveRequest' => 'Leave Request',
    'calendarView' => 'Takvim Görünümü',
    'tableView' => 'Tablo görünümü',
    'addLeave' => 'İzin Ekle',
    'editLeave' => 'İzin Düzenle',
    'leaveDate' => 'Ayrılış tarihi',
    'rejectReason' => 'Reddetme Nedeni',
  ),
  'low' => 'Düşük',
  'lead' =>
  array(
    'leadCategory' => 'Lead Category',
    'createTitle' => 'Add Lead Info',
    'companyDetails' => 'Şirket Detayları',
    'companyName' => 'Şirket Adı',
    'website' => 'İnternet sitesi',
    'address' => 'Adres',
    'leadDetails' => 'Lead Details',
    'clientName' => 'Müvekkil Adı',
    'clientEmail' => 'Müvekkil E-posta',
    'emailNote' => 'Lead will login using this email.',
    'password' => 'Şifre',
    'passwordNote' => 'Müvekkil bu şifreyi kullanarak giriş yapacaktır.',
    'passwordUpdateNote' => 'Müvekkil bu şifreyi kullanarak giriş yapacaktır. (Mevcut şifreyi saklamak için boş bırakın)',
    'mobile' => 'Mobil',
    'updateTitle' => 'Update Lead Info',
    'addNewLead' => 'Add New Lead',
    'viewDetails' => 'Detayları göster',
    'leadSource' => 'Lead Source',
    'leadStatus' => 'Lead Status',
    'leadFollowUp' => 'Sonrakini Takip Et',
    'remark' => 'Açıklama',
    'proposal' => 'Teklif',
    'profile' => 'Profil',
    'followUp' => 'Takip et',
    'note' => 'Not',
    'email' => 'E-posts',
    'source' => 'Kaynak',
    'status' => 'Durum',
    'leadDetail' => 'Lead Detail',
    'nextFollowUp' => 'Sonraki Takip',
    'all' => 'Herşey',
    'lead' => 'Lead',
    'client' => 'Müvekkil',
    'pending' => 'Bekliyor',
    'changeToClient' => 'Müvekkili Değiştir',
    'addFollowUp' => 'Takip Ekle',
    'edit' => 'Düzenle',
    'action' => 'Aksiyon',
    'view' => 'Görünüm',
    'file' => 'Dosyalar',
    'leadAgent' => 'Lead Agent',
    'kanbanboard' => 'Kanban Board',
    'defaultLeadStatus' => 'Default Lead Status',
    'leadForm' => 'Lead Form',
    'iframeSnippet' => 'Iframe Code Snippet',
    'viewPublicForm' => 'Genel Formu Görüntüle',
    'client_name' =>'İsim',
    'client_email'=>'E-posta',
    'company_name'=>'Şirket Adı',
    'message'=>'Mesaj',
    'name'=>'İsim',
  ),
  'proposal' =>
  array(
    'createTitle' => 'Teklif Bilgisi Ekle',
    'updateTitle' => 'Teklif Bilgilerini Güncelle',
    'addNewLead' => 'Yeni Teklif Ekle',
    'viewDetails' => 'Detayları göster',
    'title' => ' Lead Proposal',
    'proposal' => ' Lead Proposal',
    'createProposal' => 'Teklif Oluştur',
    'validTill' => 'Kadar geçerli',
    'waiting' => 'Beklemek',
    'accepted' => 'Kabul Edildi',
    'declined' => 'Reddedildi',
    'updateProposal' => 'Teklifi Güncelle',
    'convertProposalTitle' => 'Teklifi Faturaya Dönüştür',
    'edit' => 'Düzenle',
    'action' => 'Aksiyon',
    'view' => 'Görünüm',
    'delete' => 'Sil',
    'download' => 'İndir',
    'publicLink' => 'Herkese Açık Bağlantı',
    'rejectConfirm' => 'Reject Confirm',
    'requireSignature' => 'Onay için müvekkil imzası gerektir',
    'sendProposal' => 'Teklif Gönder',
    'convertInvoice'=>'Faturayı Dönüştür',  
  ),
  'followup' =>
  array(
    'newFollowUp' => 'Yeni Takip',
    'updateFollow' => 'Güncelleme Takibi',
    'addNewLead' => 'Yeni Teklif Ekle',
    'viewDetails' => 'Detayları göster',
    'title' => ' Lead Proposal',
    'proposal' => ' Lead Proposal',
    'createProposal' => 'Teklif Oluştur',
    'validTill' => 'Kadar geçerli',
    'waiting' => 'Beklemek',
    'accepted' => 'Kabul edildi',
    'declined' => 'Reddedildi',
    'updateProposal' => 'Teklifi Güncelle',
    'convertProposalTitle' => 'Teklifi Faturaya Dönüştür',
    'followUpNotFound' => 'Takip bulunamadı',
    'followUpNote' => 'Takip ekleme ve düzenleme işlevi, müşteri adayı <b>bir sonraki takip</b> <b>EVET</b> olduğunda çalışır.',
  ),
  'holiday' =>
  array(
    'title' => 'Tatil',
    'addNewHoliday' => 'Tatil Ekle',
    'viewDetails' => 'Detayları göster',
    'createHoliday' => 'Tatil Oluştur',
    'followUpNotFound' => 'Tatil bulunamadı',
    'markSunday' => ' Varsayılan Tatilleri İşaretle',
    'date' => 'Tarih',
    'occasion' => 'Fırsat',
    'day' => 'Gün',
    'action' => 'Aksiyon',
    'listOf' => 'Listesi',
    'viewOnCalendar' => 'Takvimde Görüntüle',
    'markHoliday' => 'Tatili İşaretle',
    'officeHolidayMarkDays' => 'Tatil için işaret günü',
  ),
  'offlinePayment' =>
  array(
    'title' => 'Çevrimdışı Ödeme Yöntemi',
    'method' => 'Yöntem',
    'description' => 'Açıklama',
    'addMethod' => 'Yöntem Ekle',
    'active' => 'Aktif',
    'inActive' => 'Aktif değil',
  ),
  'projectTemplate' =>
  array(
    'addNewTemplate' => 'Yeni Şablon Ekle',
    'projectName' => 'Şablon Adı',
    'projectMembers' => 'Şablon Üyeler',
    'createTitle' => 'Şablon Şablonu Ekle',
    'selectClient' => 'Müvekkil Seç',
    'startDate' => 'Başlangıç tarihi',
    'deadline' => 'Son teslim tarihi',
    'projectSummary' => 'Şablon Özeti',
    'note' => 'Not',
    'updateTitle' => 'Şablon Ayrıntılarını Güncelle',
    'projectCategory' => 'Şablon Kategorisi',
    'clientFeedback' => 'Müşteri Geribildirimi',
    'projectCompletionStatus' => 'Şablon Tamamlama Durumu',
    'overview' => 'Genel Bakış',
    'members' => 'Üyeler',
    'files' => 'Dosyalar',
    'activeTimers' => 'Aktif Zamanlayıcılar',
    'whoWorking' => 'Kim Çalışıyor',
    'activeSince' => 'Aktif Olduğu Tarih',
    'openTasks' => 'Açık Görevler',
    'daysLeft' => 'Kalan günler',
    'hoursLogged' => 'Günlüğe Kaydedilen Saatler',
    'issuesPending' => 'Bekleyen Sorunlar',
    'activityTimeline' => 'Etkinlik Zaman Çizelgesi',
    'addMemberTitle' => 'Şablon Üyeleri Ekle',
    'uploadFile' => 'Dosya yükleme',
    'dropFile' => 'Dosyaları buraya bırakın VEYA yüklemek için tıklayın',
    'projectUpdated' => ' proje detayları güncellendi.',
    'noOpenTasks' => 'Açık görev yok.',
    'calculateTasksProgress' => 'Görevler aracılığıyla ilerlemeyi hesaplayın',
    'viewGanttChart' => 'Gantt Chart',
    'clientViewTask' => 'Müvekkil bu projenin görevlerini yönetebilir',
    'clientTaskNotification' => 'Müvekkile görev bildirimi gönderilsin mi?',
    'manualTimelog' => 'Manuel zaman günlüklerine izin verilsin mi?',
  ),
  'templateTasks' =>
  array(
    'newTask' => 'Yeni Şablon Görevi',
    'lastCreated' => 'Son Oluşturulan',
    'dueSoon' => 'Yakında Teslim',
    'assignTo' => 'Atandı',
    'high' => 'Yüksek',
    'medium' => 'Orta',
    'low' => 'Düşük',
    'priority' => 'Öncelik',
    'updateTask' => 'Şablon Görevini Güncelle',
    'chooseAssignee' => 'Atanan Seç',
    'taskDetail' => 'Şablon Görev Ayrıntısı',
    'taskBoard' => 'Şablon Görev Panosu',
    'addBoardColumn' => 'Sütun Ekle',
    'columnName' => 'Sütun adı',
    'labelColor' => 'Etiket Rengi',
    'tasksTable' => 'Görevler Tablosu',
    'position' => 'Durum',
    'subTask' => 'Alt Şablon Görevi',
    'comment' => 'Yorum Yap',
  ),
  'logTimeSetting' =>
  array(
    'title' => 'Günlük Zaman Ayarı',
    'project' => 'Proje',
    'task' => 'Görev',
    'autoStopTimerAfterOfficeTime' => 'Ofis saatinden sonra zamanlayıcıyı otomatik olarak durdurun.',
    'approvalRequired' => 'Zaman günlüğü onay gerektirecek',
  ),
  'taskCategory' =>
  array(
    'addTaskCategory' => 'Görev Kategorisi',
    'categoryName' => 'Kategori adı',
    'manageTaskCategory' => 'Görev Kategorisini Yönet',
    'taskCategory' => 'Görev Kategorisi',
  ),
  'pushSettings' =>
  array(
    'updateTitle' => 'Anında Bildirim Ayarlarını Güncelle',
    'oneSignalAppId' => 'Tek Sinyal Uygulama Kimliği',
    'oneSignalRestApiKey' => 'Tek Sinyal Dinlenme API Anahtarı',
  ),
  'stripeSettings' =>
  array(
    'title' => 'Stripe Ayarları',
    'apiKey' => 'API Anahtarı',
    'apiSecret' => 'API Gizli',
    'webhookKey' => 'Webhook Key Secret',
    'subtitle' => 'Stripe kimlik bilgileri',
  ),
  'frontCms' =>
  array(
    'updateTitle' => 'Ön Detayı Güncelle',
    'headerTitle' => 'Üst Başlık',
    'frontDetail' => 'Ön Detay',
    'featureDetail' => 'Özellik Detayı',
    'headerDescription' => 'Başlık Açıklaması',
    'mainImage' => 'Başlık görüntü',
    'featureTitle' => 'Özellik Başlığı',
    'featureDescription' => 'Özellik Açıklama',
    'priceDetail' => 'Fiyat Detayı',
    'priceTitle' => 'Fiyat Başlığı',
    'priceDescription' => 'Fiyat Açıklama',
    'contactDetail' => 'İletişim bilgisi',
    'getStartedButtonShow' => 'Başla düğmesini göster',
    'singInButtonShow' => 'Oturum açma düğmesini göster',
    'pickPlan' => 'Planını seç',
    'perYear' => 'Yıl başına',
    'perMonth' => 'Her ay',
    'getStarted' => 'Başlamak',
    'submitEnquiry' => 'Anket Gönder',
    'socialLinks' => 'Sosyal Bağlantılar',
    'facebook' => 'Facebook',
    'twitter' => 'Twitter',
    'instagram' => 'Instagram',
    'dribbble' => 'Dribbble',
    'enterFacebookLink' => 'Facebook Bağlantısını Girin',
    'enterTwitterLink' => 'Twitter Bağlantısını Girin',
    'enterInstagramLink' => 'Instagram Bağlantısını Girin',
    'enterDribbbleLink' => 'Dribbble Bağlantısını Girin',
    'enterSocialLinks' => 'Lütfen sosyal bağlantıları girin',
    'socialLinksNote' => 'Not: Giriş Sayfasında gizlemek için girişi boş bırakın.',
    'primaryColor' => 'Ana renk',
    'widgetName' => 'Widget adı',
    'widgetCode' => 'Widget Kodu',
    'seoDetails' => 'SEO Ayrıntıları',
    'seo_title' => 'Meta başlık',
    'seo_author' => 'Meta yazar',
    'seo_description' => 'Meta Açıklaması',
    'seo_keywords' => 'Anahtar kelimeler',
    'customCss' => 'Özel Css',
    'defaultLanguage' => 'Varsayılan dil',
    'commonSettings' => 'Genel Ayarlar',
  ),
  'featureSetting' =>
  array(
    'addFeature' => 'Özellik Ekle',
    'editFeature' => 'Özelliği Düzenle',
  ),
  'feature' =>
  array(
    'setting' => 'Özellik Ayarı',
  ),
  'frontSettings' =>
  array(
    'title' => 'Ön yüz CMS',
  ),
  'module' =>
  array(
    'attendance' => 'Katılım',
    'clients' => 'Müvekkiller',
    'employees' => 'Çalışanlar',
    'estimates' => 'Tahminler',
    'events' => 'Etkinlikler',
    'expenses' => 'Masraflar',
    'holidays' => 'Bayram',
    'invoices' => 'Faturalar',
    'leads' => 'Leads',
    'leaves' => 'Leaves',
    'messages' => 'Mesajlar',
    'notice board' => 'Bildirim Panosu',
    'noticeBoard' => 'Bildirim Panosu',
    'notices' => 'Bildirimler',
    'payments' => 'Ödemeler',
    'products' => 'Ürünler',
    'projects' => 'Projeler',
    'tasks' => 'Görevler',
    'tickets' => 'Tickets',
    'timelogs' => 'Zaman Günlükleri',
    'creditNotes' => 'Kredi notu',
    'contracts' => 'Sözleşmeler',
    'reports' => 'Raporlar',
    'assets' => 'Varlıklar',
    'asset' => 'Varlıklar',
    'payroll' => 'Maaş bordrosu',
    'restApi' => 'RestAPI',
    'gitlab' => 'GITLAB',
    'sms' => 'SMS',
    'Zoom' => 'Zoom',
    'ticket support' => 'Ticket Support',
  ),
  'paymentSetting' =>
  array(
    'paypal' => 'Paypal',
    'stripe' => 'Stripe',
    'paypalClientId' => 'Paypal Müşteri Kimliği',
    'paypalSecret' => 'Paypal Secret',
    'stripeClientId' => 'Yayınlanabilir Anahtar',
    'stripeSecret' => 'Stripe Secret',
    'stripeWebhookSecret' => 'Stripe Webhook Secret',
    'razorpay' => 'Razorpay',
    'payStack' => 'Paystack',
    'paystackStatus' => 'Paystack Durumu',
    'mollieStatus' => 'Mollie Durumu',
    'authorizeStatus' => 'Authorize.net Durumu',
    'selectEnvironment' => 'Ortam seçin',
    'RazorpayKey' => 'Razorpay Key',
    'razorpaySecretKey' => 'Razorpay Secret Key',
    'razorpayWebhookSecretKey' => 'Razorpay Webhook Secret Key',
    'paystackKey' => 'Paystack Key',
    'PaystackSecretKey' => 'Paystack Secret Key',
    'paystackMerchantEmail' => 'Paystack Satıcı E-postası',
    'mollieApiKey' => 'Mollie API Anahtarı',
    'authorizeApiLoginId' => 'Api Giriş Kimliğini Yetkilendir',
    'authorizeTransactionKey' => 'İşlem Anahtarını Yetkilendir',
    'authorizeSignatureKey' => 'İmza Anahtarını Yetkilendir',
  ),
  'packageSetting' =>
  array(
    'noOfDays' => 'Gün sayısı',
    'notificationBeforeDays' => 'Günlerden Önce Bildirim',
    'trialMessage' => 'Ön sayfada gösterilen Deneme Mesajı',
  ),
  'package' =>
  array(
    'stripeAnnualPlanId' => 'Stripe Yılık Plan Kimliği',
    'stripeMonthlyPlanId' => 'Stripe Aylık Plan Kimliği',
    'razorpayAnnualPlanId' => 'Razorpay Yılık Plan Kimliği',
    'razorpayMonthlyPlanId' => 'Razorpay Aylık Plan Kimliği',
    'paystackAnnualPlanId' => 'Paystack Yılık Plan Kimliği',
    'paystackMonthlyPlanId' => 'Paystack Aylık Plan Kimliği',
    'privateInfo' => 'Özel paket müşteriler tarafından görülmez ancak superadmin, superadmin panelinden onlara atayabilir.',
    'isRecommended' => 'Önerilen olarak işaretle?',
    'licenseExpiresOn' => 'Lisans Sona Erme Tarihi',
  ),
  'credit-notes' =>
  array(
    'currency' => 'Para birimi',
    'creditNoteDate' => 'Kredi Notu Tarihi',
    'isRecurringPayment' => 'Yinelenen bir ödeme mi?',
    'item' => 'Öğe',
    'qty' => 'Qty/Hrs',
    'unitPrice' => 'Birim fiyat',
    'tax' => 'Vergi',
    'amount' => 'Miktar',
    'addItem' => 'Öğe eklemek',
    'subTotal' => 'Ara toplam',
    'discount' => 'İndirim',
    'total' => 'Toplam',
    'paid' => 'Ücretli',
    'unpaid' => 'Ücretsiz',
    'partial' => 'Kısmi',
    'addCreditNote' => 'Kredi Notu Ekle',
    'billingFrequency' => 'Faturalandırma Sıklığı',
    'billingInterval' => 'Faturalandırma Aralığı',
    'billingCycle' => 'Fatura döngüsü',
    'billedTo' => 'Fatura',
    'generatedBy' => 'Oluşturan',
    'price' => 'Fiyat',
    'downloadPdf' => 'PDF İndir',
    'creditAmountTotal' => 'Kredi Tutarı Toplam',
    'creditAmountRemaining' => 'Kalan Kredi Tutarı',
    'creditAmountUsed' => 'Kullanılan Kredi Tutarı',
    'applyToInvoice' => 'Faturaya Kredi Uygula',
    'noInvoicesFound' => 'Bu proje için kullanılabilir fatura yok.',
    'closed' => 'Kapalı',
    'open' => 'Açık',
    'uploadInvoice' => 'Fatura Yükle',
  ),
  'superadmin' =>
  array(
    'details' => 'Ayrıntılar',
    'verified' => 'Doğrulandı',
    'registerDate' => 'Kayıt Tarihi',
    'totalUsers' => 'Toplam Kullanıcılar',
    'recentRegisteredCompanies' => 'Son Kayıtlı Şirketler',
    'recentSubscriptions' => 'Son Abonelikler',
    'recentLicenseExpiredCompanies' => 'Son Lisans Süresi Dolan Şirketler',
    'disableFrontendSite' => 'Ön Yüz Sitesini Devre Dışı Bırak',
    'setupHomepage' => 'Ana Sayfayı Ayarla',
    'defaultLanding' => 'Tema Ana Sayfası',
    'customUrl' => 'Özel URL',
    'loadCustomUrl' => 'Özel URL´yi Yükle',
    'loginAsCompany' => 'Şirket Olarak Taklit Et',
  ),
  'billing' =>
  array(
    'yourCurrentPlan' => 'Mevcut Planınız',
    'unsubscribe' => 'Aboneliği iptal et',
    'changePlan' => 'Plan değiştir',
    'nextPaymentDate' => 'Sonraki Ödeme Tarihi',
    'previousPaymentDate' => 'Önceki Ödeme Tarihi',
    'choosePlan' => 'Planı Seç',
  ),
  'company' =>
  array(
    'accountSetup' => 'Hesap Detayları',
    'verifyNow' => 'Şimdi doğrulayın',
  ),
  'projectSettings' =>
  array(
    'sendNotificationsTo' => 'Hatırlatıcı Gönder',
  ),
  'hrs' => 'hrs',
  'mins' => 'mins',
  'footer' =>
  array(
    'setting' => 'Altbilgi Menü Ayarı',
    'addFooter' => 'Alt Bilgi Menüsü Ekle',
    'editFooter' => 'Altbilgi Menüsünü Düzenle',
    'footerCopyrightText' => 'Altbilgi Telif Hakkı Metni',
    'addFooterMenu' => 'Menu Details',
  ),
  'leave' =>
  array(
    'leaveRequest' => 'İzin Talebi Alındı',
  ),
  'contracts' =>
  array(
    'createContract' => 'Sözleşme Oluştur',
    'createContractType' => 'Sözleşme Türü Oluştur',
    'contractType' => 'Sözleşme Tipi',
    'summery' => 'Özet',
    'discussion' => 'Tartışma',
    'addComment' => 'Yorum ekle',
    'contractValue' => 'Sözleşme Değeri',
    'contractNumber' => 'Sözleşme numarası',
    'endDate' => 'Bitiş tarihi',
    'totalContracts' => 'Toplam Sözleşmeler',
    'expired' => 'Süresi doldu',
    'active' => 'Aktif',
    'aboutToExpire' => 'Süresi Dolmak Üzere',
    'manageContractType' => 'Sözleşme Türünü Yönet',
    'addContractType' => 'Sözleşme Türü Ekle',
    'notes' => 'Notlar',
    'editDiscussion' => 'Tartışmayı Düzenle',
    'discussionUpdated' => 'Tartışma başarıyla güncellendi.',
    'discussionDeleted' => 'Tartışma başarıyla silindi.',
    'discussionAdded' => 'Tartışma başarıyla eklendi.',
    'renewContract' => 'Sözleşme yenilemek',
    'renewedThisContract' => 'bu sözleşmeyi yeniledi',
    'newStartDate' => 'Yeni başlangıç tarihi',
    'newEndDate' => 'Yeni bitiş tarihi',
    'newAmount' => 'Yeni miktar',
    'contractRenewalHistory' => 'Sözleşme Yenileme Geçmişi',
    'contractCommect' => 'Sözleşme ile ilgili yorum',
    'noAmount'=> 'Miktar yok',
    'noEndDate' =>'Bitiş Tarihi Yok',
    'contractName'=>'Sözleşme Adı',
    'alternateAddress'=>'Alternatif Adres',
    'companyLogo'=>'Şirket Logosu',
    'summary'=>'Özet',
  ),
  'burndown' =>
  array(
    'actual' => 'Gerçek',
    'ideal' => 'İdeal',
  ),
  'clients' =>
  array(
    'addShippingAddress' => 'Teslimat Adresi Ekle',
    'shippingAddress' => 'Gönderi Adresi',
    'officePhoneNumber' => 'Ofis Telefon Numarası',
    'clientCategory' => 'Müvekkil Kategorisi',
    'clientSubCategory' => 'Müvekkil Alt Kategorisi',
    'subcategoryName' => 'Alt Kategori Adı',
    'country' =>'Ülke'
  ),
  'discussions' =>
  array(
    'lastCreated' => 'Son Oluşturulan',
    'lastModified' => 'Son düzenlenen',
    'discussionCategory' => 'Tartışma Kategorisi',
    'replied' => 'yanıtladı',
    'posted' => 'Yayınlanan',
    'bestReply' => 'En İyi Cevap',
    'removeBestReply' => 'En İyi Yanıt Olarak Taşı',
    'goBestReply' => 'En İyi Yanıta Git',
  ),
  'stripeCustomerAddress' =>
  array(
    'details' => 'Adres Detayları',
    'name' => 'İsim',
    'line1' => 'Çizgi 1',
    'postalCode' => 'Posta kodu',
    'city' => 'Şehir',
    'state' => 'Durum',
    'country' => 'Ülke',
  ),
  'footerSettings' =>
  array(
    'useDescription' => 'Açıklamayı Kullan',
    'useExternalLink' => 'Harici Bağlantı Kullan',
    'pageContent' => 'Sayfa içeriği',
    'externalLink' => 'Harici Bağlantı',
  ),
  'taskLabel' =>
  array(
    'createLabel' => 'Etiket Oluştur',
  ),
  'faq' =>
  array(
    'uploadImage' => 'Fotoğraf yükleniyor',
  ),
  'modules' =>
  array(
    'tickets' =>
    array(
      'open' => 'Açık',
      'pending' => 'Bekliyor',
      'resolved' => 'çözüldü',
      'closed' => 'Kapalı',
    ),
  ),
  'productCategory' =>
  array(
    'subCategory' => 'Alt Kategori',
    'subCategoryName' => 'Alt Kategori Adı',
    'category' => 'Kategori',
    'productCategory' => 'Ürün Kategorisi',
    'productSubCategory' => 'Ürün Alt Kategorisi',
  ),
  'expenseCategory' =>
  array(
    'addExpenseCategory' => 'Gider Kategorisi Ekle',
    'categoryName' => 'Kategori Adı',
  ),
  'recurringInvoice' =>
  array(
    'allowToClient' => 'Müvekkil tekrarlamayı durdurabilir.',
  ),
  'leads' =>
  array(
    'name' => 'Ad',
    'email' => 'E-posta',
    'company_name' => 'Şirket Adı',
    'website' => 'İnternet sitesi',
    'address' => 'Adres',
    'mobile' => 'Mobil',
    'message' => 'Mesaj',
  ),
  'gantt' =>
  array(
    'task_name' => 'Görev adı',
    'start_time' => 'Başlangıç saati',
    'duration' => 'Süre',
    'action' => 'Aksiyon',
  ),
  'emailNotification' =>
  array(
    'new-expenseadded-by-admin' => 'Yeni Gider/Yönetici Tarafından Eklendi',
    'new-expenseadded-by-member' => 'Yeni Gider/Üye Tarafından Eklendi',
    'expense-status-changed' => 'Gider Durumu Değiştirildi',
    'user-registrationadded-by-admin' => ' Kullanıcı Kaydı/Yönetici Tarafından Eklendi',
    'employee-assign-to-project' => 'Projeye Çalışan Ataması',
    'new-notice-published' => 'Yeni Bildirim Yayınlandı',
    'user-assign-to-task' => 'Kullanıcı Göreve Ata',
    'new-leave-application' => 'Yeni İzin Başvurusu',
    'task-completed' => 'Görev tamamlandı',
    'invoice-createupdate-notification' => 'Fatura Oluştur/Güncelle Bildirimi',
    'payment-createupdate-notification' => 'Ödeme Oluştur/Güncelle Bildirimi',
    'discussion-reply' => 'Tartışma Yanıtı',
    'new-proposal' => 'Yeni teklif',
    'lead-notification' => 'Lead notification',
    'new-support-ticket-request' => 'New Support Ticket Request',
  ),
);
