<?php

return array (
  'accepted' => ':özellik kabul edilmelidir.',
  'active_url' => ':özellik geçerli bir URL değil.',
  'after' => ':özellik, :tarih tarihinden sonraki bir tarih olmalıdır.',
  'after_or_equal' => ':özellik, :tarih`den sonraki veya buna eşit bir tarih olmalıdır.',
  'alpha' => ':özellik yalnızca harf içerebilir.',
  'alpha_dash' => ':özellik yalnızca harf, sayı ve tire içerebilir.',
  'alpha_num' => ':özellik yalnızca harf ve sayı içerebilir.',
  'array' => ':özellik bir dizi olmalıdır.',
  'before' => ':özellik, :tarih tarihinden önceki bir tarih olmalıdır.',
  'invalidEmail' => 'Lütfen geçerli bir e-posta adresi giriniz.',
  'invalidEmailPassword' => 'E-posta ve şifre kombinasyonu doğru değil.',
  'givenDataInvalid' => 'Verilen veriler geçersizdi.',
  'before_or_equal' => ':özellik, :tarih tarihinden önce veya buna eşit bir tarih olmalıdır.',
  'between' => 
  array (
    'numeric' => ':özellik :min ve :max arasında olmalıdır.',
    'file' => ':özellik :min ve :max kilobaytlar arasında olmalıdır.',
    'string' => ':özellik :min ve :max karakterleri arasında olmalıdır.',
    'array' => ':özellik, :min ve :max öğeleri arasında olmalıdır.',
  ),
  'boolean' => ':özellik alanı doğru veya yanlış olmalıdır.',
  'confirmed' => ':özellik onayı eşleşmiyor.',
  'date' => ':özellik geçerli bir tarih değil.',
  'date_format' => ':özellik, :biçim biçimiyle eşleşmiyor.',
  'different' => ':özellik ve :diğer farklı olmalıdır.',
  'digits' => ':özellik :digits rakamlardan oluşmalıdır.',
  'digits_between' => ':özellik :min ve :max basamakları arasında olmalıdır.',
  'dimensions' => ':özellik geçersiz resim boyutlarına sahip.',
  'distinct' => ':özellik alanı yinelenen bir değere sahip.',
  'email' => ':özellik geçerli bir e-posta adresi olmalıdır.',
  'exists' => 'Seçilen :özellik geçersiz.',
  'file' => ':özellik bir dosya olmalıdır.',
  'filled' => ':özellik alanı bir değere sahip olmalıdır.',
  'image' => ':özellik bir resim olmalıdır.',
  'in' => 'Seçilen :özellik geçersiz.',
  'in_array' => ':özellik alanı :diğer içinde mevcut değil.',
  'integer' => ':özellik bir tamsayı olmalıdır.',
  'ip' => ':özellik geçerli bir IP adresi olmalıdır.',
  'json' => ':özellik geçerli bir JSON dizesi olmalıdır.',
  'max' => 
  array (
    'numeric' => ':özellik :max değerinden büyük olamaz.',
    'file' => ':özellik :max kilobayttan büyük olamaz.',
    'string' => ':özellik :max karakterden büyük olamaz.',
    'array' => ':özellik öğesi, :max öğelerinden daha fazlasına sahip olamaz.',
  ),
  'mimes' => ':özellik, :değerler türünde bir dosya olmalıdır.',
  'mimetypes' => ':özellik, :değerler türünde bir dosya olmalıdır.',
  'min' => 
  array (
    'numeric' => ':özellik en az :min olmalıdır.',
    'file' => ':özellik en az :min kilobayt olmalıdır.',
    'string' => ':özellik en az :min karakter olmalıdır.',
    'array' => ':özellik en az :min öğelerine sahip olmalıdır.',
  ),
  'not_in' => 'Seçilen :özellik geçersiz.',
  'numeric' => ':özellik bir sayı olmalıdır.',
  'present' => ':özellik alanı mevcut olmalıdır.',
  'regex' => ':özellik biçimi geçersiz.',
  'required' => ':özellik alanı gereklidir.',
  'required_if' => ':özellik alanı, :diğer :değerler olduğunda gereklidir.',
  'required_unless' => ':özellik alanı, :diğer :değerler içinde olmadıkça gereklidir.',
  'required_with' => ':özellik alanı, :değerler mevcut olduğunda gereklidir.',
  'required_with_all' => ':özellik alanı, :değerler mevcut olduğunda gereklidir.',
  'required_without' => ':özellik alanı, :değerler olmadığında gereklidir.',
  'required_without_all' => ':özellik alanı, :değerler değerlerinin hiçbiri mevcut olmadığında gereklidir.',
  'same' => ':özellik ve :diğer eşleşmelidir.',
  'size' => 
  array (
    'numeric' => ':özellik :boyut olmalıdır.',
    'file' => ':özellik :boyut kilobayt olmalıdır.',
    'string' => ':özellik :boyut karakter olmalıdır.',
    'array' => ':özellik :boyut öğeleri içermelidir.',
  ),
  'string' => ':özellik bir dize olmalıdır.',
  'timezone' => ':özellik geçerli bir bölge olmalıdır.',
  'unique' => ':özellik zaten alınmış.',
  'uploaded' => ':özellik yüklenemedi.',
  'url' => ':özellik geçerli bir url değil.Örneğin:http://abc.com',
  'custom' => 
  array (
    'attribute-name' => 
    array (
      'rule-name' => 'özel-mesaj',
    ),
  ),
);
